const TIPO_OPERACION = {
  /*OPERACION ARITMETICA*/
  SUMA: 'OP_SUMA',
  RESTA: 'OP_RESTA',
  MULTIPLICACION: 'OP_MULTIPLICACION',
  DIVISION: 'OP_DIVISION',
  POTENCIA: 'OP_POTENCIA',
  MODULO: 'OP_MODULO',
  INCREMENTO: 'OP_INCREMENTO',
  DECREMENTO: 'OP_DECREMENTO',

  /**/
  MAYOR_QUE: 'OP_MAYOR_QUE',
  MENOR_QUE: 'OP_MENOR_QUE',
  MAYOR_IGUAL: 'OP_MAYOR_IGUAL',
  MENOR_IGUAL: 'OP_MENOR_IGUAL',

}
